<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ReplScope</AssemblyName>
    <RootNamespace>ReplScope</RootNamespace>
    <Version>1.3.1</Version>
    <Product>ReplScope</Product>
    <Description>Moniteur de réplication Active Directory (lecture seule)</Description>
    <ApplicationIcon>Assets\ReplScope.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\logo.png" LogicalName="logo.png" />
  </ItemGroup>
</Project>
